# Generated by Django 4.2.1 on 2023-06-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disability', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id_sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, primary_key=True, serialize=False, verbose_name='sex_id')),
                ('gender', models.CharField(max_length=50, verbose_name='gender')),
            ],
            options={
                'db_table': 'sexos',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(verbose_name='age')),
                ('start_year', models.IntegerField(verbose_name='start_year')),
                ('disability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disability.disability')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.sex')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
    ]
