# Generated by Django 4.2.1 on 2023-06-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('acronyms', models.CharField(max_length=10, unique=True, verbose_name='acronyms')),
            ],
            options={
                'db_table': 'universidades',
            },
        ),
    ]
